#!/usr/bin/env bash
# =============================================================================
# GusVoice — turnkey installer.
#
#   curl -fsSL https://raw.githubusercontent.com/Gleb1290/gusvoice/main/install.sh | bash
#   # or: git clone … && cd gusvoice && ./install.sh
#
# Asks a few questions, GENERATES ALL SECRETS, writes .env, and brings the whole
# stack up (postgres · redis · livekit · backend · presence · client + bundled
# Caddy/MinIO/ntfy). The only manual steps left to you: DNS records + port forwarding.
#
# Idempotent-ish: re-running keeps an existing .env (won't clobber your secrets).
# Runtime-verified end-to-end at P8 (clean VPS) — treat as a first-cut until then.
# =============================================================================
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

# Public prebuilt images (set to the project's GHCR path at P5). Override with REGISTRY/TAG env.
REGISTRY_DEFAULT="${REGISTRY:-ghcr.io/Gleb1290/gusvoice}"
TAG_DEFAULT="${TAG:-latest}"

say()  { printf '\n\033[1;36m%s\033[0m\n' "$*"; }
info() { printf '  \033[0;90m%s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mError:\033[0m %s\n' "$*" >&2; exit 1; }

gen_secret() { openssl rand -hex 32; }

ask() { # ask "Prompt" "default" -> echoes answer
  local prompt="$1" def="${2:-}" ans
  if [ -n "$def" ]; then read -r -p "$prompt [$def]: " ans; echo "${ans:-$def}"
  else read -r -p "$prompt: " ans; echo "$ans"; fi
}

# --- Prerequisites ----------------------------------------------------------
say "GusVoice installer"
command -v docker >/dev/null 2>&1 || die "docker is required (https://docs.docker.com/engine/install/)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
command -v openssl >/dev/null 2>&1 || die "openssl is required"

# --- Keep an existing .env --------------------------------------------------
if [ -f .env ]; then
  say "An .env already exists — keeping it (delete it to reconfigure from scratch)."
else
  # --- Questions ------------------------------------------------------------
  say "A few questions (press Enter to accept defaults):"
  BASE_DOMAIN="$(ask 'Your base domain (e.g. example.com)' 'example.com')"
  ACME_EMAIL="$(ask 'Email for Let'\''s Encrypt (TLS certs)' "admin@${BASE_DOMAIN}")"
  SUPERADMIN="$(ask 'Super-admin username (the account granted full access)' 'admin')"

  info "Domain mode: subdomains (voice/api/presence/lk/media/ntfy.${BASE_DOMAIN})."
  info "Single-name mode (everything under one host) is coming — subdomains for now."

  SMTP_HOST=""; SMTP_USER=""; SMTP_PASS=""; MAIL_FROM="GusVoice <noreply@${BASE_DOMAIN}>"
  if [ "$(ask 'Configure SMTP for email verification? (y/N)' 'N')" = "y" ]; then
    SMTP_HOST="$(ask 'SMTP host' '')"
    SMTP_USER="$(ask 'SMTP username' "noreply@${BASE_DOMAIN}")"
    SMTP_PASS="$(ask 'SMTP password' '')"
  fi

  # --- Generated secrets ----------------------------------------------------
  say "Generating secrets…"
  JWT_SECRET="$(gen_secret)"
  LIVEKIT_API_SECRET="$(gen_secret)"
  POSTGRES_PASSWORD="$(gen_secret)"
  MINIO_ACCESS_KEY="gusvoice"
  MINIO_SECRET_KEY="$(gen_secret)"

  # --- Public IP (for LiveKit ICE) ------------------------------------------
  PUBLIC_IP="$(curl -fsSL https://api.ipify.org 2>/dev/null || echo '')"
  [ -n "$PUBLIC_IP" ] && info "Detected public IP: $PUBLIC_IP (LiveKit will advertise it via STUN)."

  # --- Write .env -----------------------------------------------------------
  say "Writing .env…"
  cat > .env <<EOF
# Generated by install.sh — DO NOT COMMIT. Regenerate by deleting this file and re-running.
BASE_DOMAIN=${BASE_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

POSTGRES_USER=gusvoice
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=gusvoice

JWT_SECRET=${JWT_SECRET}
SUPERADMIN_USERNAME=${SUPERADMIN}
ADMIN_EMAIL=

MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET=gusvoice
MINIO_PUBLIC_URL=https://media.${BASE_DOMAIN}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
MAIL_FROM=${MAIL_FROM}

# Filled after the ntfy container is up (see below).
NTFY_BASE_URL=https://ntfy.${BASE_DOMAIN}
NTFY_TOKEN=

LIVEKIT_API_KEY=gusvoice
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
LIVEKIT_URL_EXTERNAL=wss://lk.${BASE_DOMAIN}

VITE_API_URL=https://api.${BASE_DOMAIN}
VITE_PRESENCE_WS=wss://presence.${BASE_DOMAIN}
VITE_PUSH_GATEWAY=https://ntfy.${BASE_DOMAIN}
CLIENT_ORIGIN=https://voice.${BASE_DOMAIN}

REGISTRY=${REGISTRY_DEFAULT}
TAG=${TAG_DEFAULT}
# Caddy publishes 80/443; internal services stay on the docker network.
BIND_ADDR=127.0.0.1
EOF
  chmod 600 .env
fi

# --- Bring the stack up -----------------------------------------------------
PROFILES=(--profile caddy --profile storage --profile push)
say "Pulling images…"
docker compose "${PROFILES[@]}" pull --quiet || info "(pull skipped — building locally or images not published yet)"
say "Starting the stack…"
docker compose "${PROFILES[@]}" up -d

# --- Create the ntfy publish token (once) -----------------------------------
# The backend needs a write token to publish wake payloads. anon stays read-only.
# TODO(P8): verify these ntfy CLI calls against the pinned ntfy version.
if ! grep -q '^NTFY_TOKEN=..' .env; then
  say "Provisioning the ntfy publish token…"
  sleep 5
  if docker compose "${PROFILES[@]}" exec -T ntfy ntfy user list 2>/dev/null | grep -q gusvoice; then
    info "ntfy user already exists."
  else
    NTFY_PW="$(gen_secret)"
    NTFY_PASSWORD="$NTFY_PW" docker compose "${PROFILES[@]}" exec -T -e NTFY_PASSWORD="$NTFY_PW" ntfy \
      ntfy user add --role=user gusvoice >/dev/null 2>&1 || info "(ntfy user add failed — provision the token manually)"
    docker compose "${PROFILES[@]}" exec -T ntfy ntfy access gusvoice 'up*' write >/dev/null 2>&1 || true
  fi
  TOKEN="$(docker compose "${PROFILES[@]}" exec -T ntfy ntfy token add gusvoice 2>/dev/null | grep -oE 'tk_[A-Za-z0-9]+' | head -n1 || true)"
  if [ -n "$TOKEN" ]; then
    # Portable in-place edit (BSD/GNU sed differ) — rewrite the line.
    grep -v '^NTFY_TOKEN=' .env > .env.tmp && echo "NTFY_TOKEN=${TOKEN}" >> .env.tmp && mv .env.tmp .env
    chmod 600 .env
    docker compose "${PROFILES[@]}" up -d backend
    info "ntfy token stored; backend restarted with push enabled."
  else
    info "Could not auto-create the ntfy token — push is off until you set NTFY_TOKEN in .env."
  fi
fi

# --- Done -------------------------------------------------------------------
BASE_DOMAIN="$(grep '^BASE_DOMAIN=' .env | cut -d= -f2)"
PUBLIC_IP="${PUBLIC_IP:-<your-server-public-IP>}"
say "GusVoice is up. Two manual steps remain:"
cat <<EOF

  1) DNS — point these at your server (a wildcard A-record *.${BASE_DOMAIN} covers them all):
       voice.${BASE_DOMAIN}     api.${BASE_DOMAIN}       presence.${BASE_DOMAIN}
       lk.${BASE_DOMAIN}        media.${BASE_DOMAIN}     ntfy.${BASE_DOMAIN}
     -> ${PUBLIC_IP}

  2) Ports — open / forward on your firewall/router to this host:
       80/tcp, 443/tcp   (web + HTTPS, handled by Caddy)
       7881/tcp, 7882/udp (LiveKit media — direct, NOT proxied)

  Then open  https://voice.${BASE_DOMAIN}  and register the "${SUPERADMIN:-admin}" account.
  Desktop/Android clients: download from the project's Releases, then enter  voice.${BASE_DOMAIN}  at login.

EOF
