/**
 * Рукописные шорткоды с РУССКИМИ алиасами. Только данные — ни одного импорта, чтобы этот модуль
 * могли тянуть и API-слой (emojiShortcodes.ts), и ленивый индекс (emojiIndex.ts) без цикла.
 *
 * Зачем он рядом с юникодной таблицей на 1914 эмодзи: там английские шорткоды вида «:fire:», а
 * «:огонь» и «:лайк» есть только здесь. Плюс этот набор доступен МГНОВЕННО, до загрузки таблицы.
 */
export type EmojiEntry = { emoji: string; codes: string[] };

export const EMOJI_SHORTCODES: EmojiEntry[] = [
  { emoji: '😀', codes: ['grinning', 'улыбка'] },
  { emoji: '😄', codes: ['smile', 'смех', 'улыб'] },
  { emoji: '😁', codes: ['grin'] },
  { emoji: '😂', codes: ['joy', 'слезы', 'ржу'] },
  { emoji: '🤣', codes: ['rofl', 'ржака'] },
  { emoji: '😊', codes: ['blush', 'смущ'] },
  { emoji: '🙂', codes: ['slight_smile'] },
  { emoji: '🙃', codes: ['upside_down'] },
  { emoji: '😉', codes: ['wink', 'подмиг'] },
  { emoji: '😍', codes: ['heart_eyes', 'влюб'] },
  { emoji: '🥰', codes: ['smiling_face_with_hearts', 'нежность'] },
  { emoji: '😘', codes: ['kissing_heart', 'поцелуй'] },
  { emoji: '😜', codes: ['stuck_out_tongue_winking_eye', 'язык'] },
  { emoji: '🤪', codes: ['zany', 'дурак'] },
  { emoji: '🧐', codes: ['monocle'] },
  { emoji: '🤓', codes: ['nerd', 'ботан'] },
  { emoji: '😎', codes: ['sunglasses', 'крут'] },
  { emoji: '🥳', codes: ['partying', 'вечеринка'] },
  { emoji: '😏', codes: ['smirk'] },
  { emoji: '😒', codes: ['unamused'] },
  { emoji: '😔', codes: ['pensive', 'грусть'] },
  { emoji: '😢', codes: ['cry', 'плач'] },
  { emoji: '😭', codes: ['sob', 'рыдаю'] },
  { emoji: '😤', codes: ['triumph'] },
  { emoji: '😠', codes: ['angry', 'злой'] },
  { emoji: '😡', codes: ['rage', 'бешен'] },
  { emoji: '🤬', codes: ['cursing', 'мат'] },
  { emoji: '🤯', codes: ['exploding_head', 'взрыв'] },
  { emoji: '😳', codes: ['flushed'] },
  { emoji: '🥵', codes: ['hot', 'жарко'] },
  { emoji: '🥶', codes: ['cold', 'холод'] },
  { emoji: '😱', codes: ['scream', 'ужас'] },
  { emoji: '🥺', codes: ['pleading', 'умоляю'] },
  { emoji: '🤗', codes: ['hugs', 'обним'] },
  { emoji: '🤔', codes: ['thinking', 'думаю'] },
  { emoji: '🤭', codes: ['hand_over_mouth'] },
  { emoji: '🤫', codes: ['shushing', 'тихо'] },
  { emoji: '😶', codes: ['no_mouth'] },
  { emoji: '😐', codes: ['neutral'] },
  { emoji: '🙄', codes: ['roll_eyes', 'глаза'] },
  { emoji: '😴', codes: ['sleeping', 'сплю'] },
  { emoji: '🤤', codes: ['drooling'] },
  { emoji: '🥴', codes: ['woozy', 'пьян'] },
  { emoji: '🤢', codes: ['nauseated', 'тошн'] },
  { emoji: '😷', codes: ['mask', 'маска'] },
  { emoji: '🤒', codes: ['thermometer', 'болею'] },
  { emoji: '🤑', codes: ['money_mouth', 'деньги'] },
  { emoji: '🤠', codes: ['cowboy'] },
  { emoji: '👍', codes: ['thumbsup', '+1', 'лайк', 'да'] },
  { emoji: '👎', codes: ['thumbsdown', '-1', 'дизлайк'] },
  { emoji: '👌', codes: ['ok_hand', 'ок'] },
  { emoji: '✌️', codes: ['victory', 'мир'] },
  { emoji: '🤞', codes: ['crossed_fingers', 'удача'] },
  { emoji: '🤘', codes: ['metal', 'коза'] },
  { emoji: '👋', codes: ['wave', 'привет', 'пока'] },
  { emoji: '🤝', codes: ['handshake', 'договор'] },
  { emoji: '🙏', codes: ['pray', 'спасибо', 'плиз'] },
  { emoji: '💪', codes: ['muscle', 'сила'] },
  { emoji: '👏', codes: ['clap', 'апл'] },
  { emoji: '🙌', codes: ['raised_hands', 'руки'] },
  { emoji: '✊', codes: ['fist'] },
  { emoji: '❤️', codes: ['heart', 'сердце', 'любовь'] },
  { emoji: '🧡', codes: ['orange_heart'] },
  { emoji: '💛', codes: ['yellow_heart'] },
  { emoji: '💚', codes: ['green_heart'] },
  { emoji: '💙', codes: ['blue_heart'] },
  { emoji: '💜', codes: ['purple_heart'] },
  { emoji: '🖤', codes: ['black_heart'] },
  { emoji: '💔', codes: ['broken_heart', 'разбит'] },
  { emoji: '💕', codes: ['two_hearts'] },
  { emoji: '✅', codes: ['white_check_mark', 'готово', 'done'] },
  { emoji: '❌', codes: ['x', 'нет', 'отмена'] },
  { emoji: '⭐', codes: ['star', 'звезда'] },
  { emoji: '🔥', codes: ['fire', 'огонь', 'пожар'] },
  { emoji: '✨', codes: ['sparkles', 'блеск'] },
  { emoji: '🎉', codes: ['tada', 'ура', 'праздник'] },
  { emoji: '🎊', codes: ['confetti'] },
  { emoji: '💯', codes: ['100', 'сотка'] },
  { emoji: '❓', codes: ['question', 'вопрос'] },
  { emoji: '❗', codes: ['exclamation', 'внимание'] },
  { emoji: '⚡', codes: ['zap', 'молния'] },
  { emoji: '💥', codes: ['boom', 'бум'] },
  { emoji: '⚠️', codes: ['warning', 'осторожно'] },
  { emoji: '🚀', codes: ['rocket', 'ракета', 'релиз'] },
  { emoji: '🏆', codes: ['trophy', 'кубок'] },
  { emoji: '🎯', codes: ['dart', 'цель'] },
  { emoji: '👀', codes: ['eyes', 'глазки', 'смотрю'] },
  { emoji: '💀', codes: ['skull', 'череп', 'умер'] },
  { emoji: '🤖', codes: ['robot', 'бот'] },
  { emoji: '💬', codes: ['speech_balloon', 'чат'] },
  { emoji: '🔔', codes: ['bell', 'звонок'] },
  { emoji: '🔒', codes: ['lock', 'замок'] },
  { emoji: '🎵', codes: ['musical_note', 'музыка'] },
  { emoji: '📌', codes: ['pushpin', 'закреп'] },
  { emoji: '🦢', codes: ['swan', 'гусь', 'goose'] },
  { emoji: '🦆', codes: ['duck', 'утка'] },
  { emoji: '🍕', codes: ['pizza', 'пицца'] },
  { emoji: '🍔', codes: ['hamburger', 'бургер'] },
  { emoji: '🍿', codes: ['popcorn', 'попкорн'] },
  { emoji: '🍩', codes: ['doughnut', 'пончик'] },
  { emoji: '🎂', codes: ['birthday', 'торт', 'др'] },
  { emoji: '🍺', codes: ['beer', 'пиво'] },
  { emoji: '🍻', codes: ['beers', 'бахнем'] },
  { emoji: '🍷', codes: ['wine', 'вино'] },
  { emoji: '☕', codes: ['coffee', 'кофе'] },
  { emoji: '🥤', codes: ['cup_with_straw'] },
  { emoji: '🎮', codes: ['video_game', 'игра', 'катка'] },
  { emoji: '🕹️', codes: ['joystick'] },
  { emoji: '💻', codes: ['computer', 'комп'] },
  { emoji: '🖥️', codes: ['desktop', 'монитор'] },
  { emoji: '📱', codes: ['phone', 'телефон'] },
  { emoji: '🎧', codes: ['headphones', 'наушники'] },
  { emoji: '🎤', codes: ['microphone', 'микро'] },
  { emoji: '📷', codes: ['camera', 'камера'] },
  { emoji: '🖼️', codes: ['picture', 'скрин'] },
  { emoji: '🐈', codes: ['cat', 'кот'] },
  { emoji: '🐕', codes: ['dog', 'пёс', 'собака'] },
  { emoji: '🌚', codes: ['new_moon_face', 'луна'] },
  { emoji: '🗿', codes: ['moai', 'моаи'] },

  // Остаток набора пикера. Каждое эмодзи, которое можно ткнуть, должно и набираться — иначе
  // подсказка «наберите :код:» молчит на половине сетки и выглядит сломанной.
  { emoji: '😃', codes: ['smiley'] },
  { emoji: '😆', codes: ['laughing', 'хохот'] },
  { emoji: '😅', codes: ['sweat_smile', 'неловко'] },
  { emoji: '😇', codes: ['innocent', 'ангел'] },
  { emoji: '😌', codes: ['relieved', 'облегчение'] },
  { emoji: '😋', codes: ['yum', 'вкусно'] },
  { emoji: '😛', codes: ['tongue', 'дразнюсь'] },
  { emoji: '🤨', codes: ['raised_eyebrow', 'бровь'] },
  { emoji: '😞', codes: ['disappointed', 'разочарован'] },
  { emoji: '😟', codes: ['worried', 'волнуюсь'] },
  { emoji: '😕', codes: ['confused', 'растерян'] },
  { emoji: '🙁', codes: ['frowning', 'хмурый'] },
  { emoji: '😣', codes: ['persevere'] },
  { emoji: '😖', codes: ['confounded'] },
  { emoji: '😫', codes: ['tired', 'устал'] },
  { emoji: '😩', codes: ['weary', 'изнемог'] },
  { emoji: '😨', codes: ['fearful', 'страшно'] },
  { emoji: '😰', codes: ['anxious', 'тревога'] },
  { emoji: '😥', codes: ['sad_relieved'] },
  { emoji: '😓', codes: ['sweat', 'пот'] },
  { emoji: '🤥', codes: ['lying', 'вру'] },
  { emoji: '😑', codes: ['expressionless'] },
  { emoji: '😬', codes: ['grimacing', 'неловкость'] },
  { emoji: '😯', codes: ['hushed', 'ого'] },
  { emoji: '😪', codes: ['sleepy', 'сонный'] },
  { emoji: '🤐', codes: ['zipper_mouth', 'молчу'] },
  { emoji: '🤮', codes: ['vomiting', 'тошнит'] },
  { emoji: '🤧', codes: ['sneezing', 'чихаю'] },
  { emoji: '🤕', codes: ['head_bandage', 'травма'] },
  { emoji: '🤌', codes: ['pinched_fingers', 'щепоть'] },
  { emoji: '🤏', codes: ['pinch', 'чуть-чуть'] },
  { emoji: '🤟', codes: ['love_you'] },
  { emoji: '🤙', codes: ['call_me', 'звони'] },
  { emoji: '👈', codes: ['point_left', 'влево'] },
  { emoji: '👉', codes: ['point_right', 'вправо'] },
  { emoji: '👆', codes: ['point_up', 'вверх'] },
  { emoji: '👇', codes: ['point_down', 'вниз'] },
  { emoji: '☝️', codes: ['index_up'] },
  { emoji: '✋', codes: ['hand', 'стоп'] },
  { emoji: '🤚', codes: ['back_of_hand'] },
  { emoji: '🖐️', codes: ['hand_splayed', 'пятерня'] },
  { emoji: '🖖', codes: ['vulcan', 'спок'] },
  { emoji: '✍️', codes: ['writing', 'пишу'] },
  { emoji: '🦾', codes: ['mechanical_arm', 'протез'] },
  { emoji: '👐', codes: ['open_hands'] },
  { emoji: '🤲', codes: ['palms_up', 'прошу'] },
  { emoji: '🤜', codes: ['fist_right'] },
  { emoji: '🤛', codes: ['fist_left'] },
  { emoji: '👊', codes: ['punch', 'кулак'] },
  { emoji: '🫶', codes: ['heart_hands', 'сердечко'] },
  { emoji: '🤍', codes: ['white_heart'] },
  { emoji: '🤎', codes: ['brown_heart'] },
  { emoji: '❣️', codes: ['heart_exclamation'] },
  { emoji: '💞', codes: ['revolving_hearts'] },
  { emoji: '💓', codes: ['heartbeat'] },
  { emoji: '💗', codes: ['heartpulse'] },
  { emoji: '💖', codes: ['sparkling_heart'] },
  { emoji: '💘', codes: ['cupid'] },
  { emoji: '💝', codes: ['gift_heart'] },
  { emoji: '💟', codes: ['heart_decoration'] },
  { emoji: '💢', codes: ['anger', 'злость'] },
  { emoji: '💫', codes: ['dizzy', 'звездочки'] },
  { emoji: '☠️', codes: ['skull_crossbones', 'пираты'] },
  { emoji: '🔕', codes: ['bell_off', 'тишина'] },
  { emoji: '🎶', codes: ['notes', 'ноты'] },
  { emoji: '🆗', codes: ['okay', 'окей'] },
  { emoji: '🆕', codes: ['new', 'новое'] },
  { emoji: '♻️', codes: ['recycle', 'переработка'] },
  { emoji: '✔️', codes: ['check', 'галка'] },
  { emoji: '➕', codes: ['plus', 'плюс'] },
  { emoji: '➖', codes: ['minus', 'минус'] },
  { emoji: '🍟', codes: ['fries', 'картошка'] },
  { emoji: '🌭', codes: ['hotdog', 'хотдог'] },
  { emoji: '🧀', codes: ['cheese', 'сыр'] },
  { emoji: '🥨', codes: ['pretzel', 'крендель'] },
  { emoji: '🥞', codes: ['pancakes', 'блины'] },
  { emoji: '🧇', codes: ['waffle', 'вафля'] },
  { emoji: '🍪', codes: ['cookie', 'печенье'] },
  { emoji: '🍰', codes: ['cake', 'тортик'] },
  { emoji: '🧁', codes: ['cupcake', 'кекс'] },
  { emoji: '🍫', codes: ['chocolate', 'шоколад'] },
  { emoji: '🍬', codes: ['candy', 'конфета'] },
  { emoji: '🍭', codes: ['lollipop', 'леденец'] },
  { emoji: '🥂', codes: ['champagne', 'шампанское'] },
  { emoji: '🍵', codes: ['tea', 'чай'] },
  { emoji: '🧃', codes: ['juice', 'сок'] },
  { emoji: '🍦', codes: ['ice_cream', 'мороженое'] },
  { emoji: '🍓', codes: ['strawberry', 'клубника'] },
  { emoji: '🍑', codes: ['peach', 'персик'] },
  { emoji: '🍉', codes: ['watermelon', 'арбуз'] },
  { emoji: '🍌', codes: ['banana', 'банан'] },
  { emoji: '🍎', codes: ['apple', 'яблоко'] },
  { emoji: '🥑', codes: ['avocado', 'авокадо'] },
  { emoji: '🍇', codes: ['grapes', 'виноград'] },
];
